"use strict";

const ExcelJS = require("exceljs");

const MONEY_FORMAT = '#,##0.00;[Red](#,##0.00);-';

function asDate(value) {
  if (!value) return null;
  if (typeof value.toDate === "function") return value.toDate();
  if (typeof value.toMillis === "function") return new Date(value.toMillis());
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function styleTable(sheet, { money = [], dates = [], headerRow = 1 } = {}) {
  sheet.views = [{ state: "frozen", ySplit: headerRow }];
  const lastColumn = sheet.columnCount;
  if (lastColumn > 0 && sheet.rowCount >= headerRow) {
    sheet.autoFilter = {
      from: { row: headerRow, column: 1 },
      to: { row: sheet.rowCount, column: lastColumn },
    };
  }
  sheet.getRow(headerRow).height = 32;
  sheet.getRow(headerRow).eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF17324D" } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
  });
  money.forEach((column) => { sheet.getColumn(column).numFmt = MONEY_FORMAT; });
  dates.forEach((column) => { sheet.getColumn(column).numFmt = "yyyy-mm-dd hh:mm"; });
  sheet.columns.forEach((column) => {
    let width = 12;
    column.eachCell({ includeEmpty: false }, (cell) => {
      width = Math.max(width, Math.min(42, String(cell.value ?? "").length + 2));
    });
    column.width = width;
  });
  for (let row = headerRow + 1; row <= sheet.rowCount; row += 1) {
    if (row % 2 === 0) {
      sheet.getRow(row).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF3F6F8" } };
    }
    sheet.getRow(row).alignment = { vertical: "top", wrapText: true };
  }
  sheet.pageSetup = { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0, paperSize: 9 };
  sheet.headerFooter.oddFooter = "&L Petsupo&C Finance Report&RPage &P of &N";
}

function addTitle(sheet, title, report) {
  sheet.mergeCells("A1:H1");
  sheet.getCell("A1").value = title;
  sheet.getCell("A1").font = { bold: true, size: 18, color: { argb: "FF17324D" } };
  sheet.getCell("A1").alignment = { vertical: "middle" };
  sheet.getRow(1).height = 32;
  const values = [
    ["Company", report.companyName],
    ["Report language", report.languageLabel],
    ["Generated at", asDate(report.generatedAt)],
    ["Generated by", report.generatedBy],
    ["Date range", report.dateRangeLabel],
    ["Filters", report.filtersLabel],
    ["Currency", report.currencyLabel],
    ["Report version", report.reportVersion],
  ];
  values.forEach(([label, value], index) => {
    sheet.getCell(index + 2, 1).value = label;
    sheet.getCell(index + 2, 1).font = { bold: true };
    sheet.getCell(index + 2, 2).value = value;
  });
  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 42;
}

function addSummary(sheet, report, labels) {
  const start = 12;
  sheet.mergeCells(start, 1, start, 4);
  sheet.getCell(start, 1).value = labels.summary;
  sheet.getCell(start, 1).font = { bold: true, size: 14, color: { argb: "FF17324D" } };
  const rows = [
    [labels.totalCustomerPayments, report.totals.customerPaid, report.currency],
    [labels.totalCommission, report.totals.commission, report.currency],
    [labels.totalSellerPayable, report.totals.sellerNet, report.currency],
    [labels.waitingAmount, report.totals.waiting, report.currency],
    [labels.eligibleAmount, report.totals.eligible, report.currency],
    [labels.blockedAmount, report.totals.blocked, report.currency],
    [labels.requiresRepairAmount, report.totals.requiresRepair, report.currency],
    [labels.batchedAmount, report.totals.batched, report.currency],
    [labels.processingAmount, report.totals.processing, report.currency],
    [labels.paidAmount, report.totals.paid, report.currency],
    [labels.refundedAmount, report.totals.refunded, report.currency],
    [labels.sellers, report.sellers.length, ""],
    [labels.transactions, report.transactions.length, ""],
    [labels.nextPayout, asDate(report.nextPayoutDate), ""],
  ];
  rows.forEach(([label, value, currency], index) => {
    const row = sheet.getRow(start + 1 + index);
    row.getCell(1).value = label;
    row.getCell(2).value = typeof value === "number" ? value : value;
    row.getCell(3).value = currency;
    row.getCell(1).font = { bold: true };
    if (typeof value === "number" && currency) row.getCell(2).numFmt = MONEY_FORMAT;
    if (value instanceof Date) row.getCell(2).numFmt = "yyyy-mm-dd";
  });
}

function addSellerSheet(workbook, report, labels) {
  const sheet = workbook.addWorksheet(labels.sellersSheet);
  const headers = [
    labels.seller, labels.legalName, labels.sector, labels.taxId, labels.accountHolder,
    labels.bank, labels.iban, labels.currency, labels.customerPaid, labels.commission,
    labels.sellerNet, labels.waiting, labels.eligible, labels.blocked, labels.batched,
    labels.paid, labels.oldestUnpaid, labels.nextEligibility, labels.daysRemaining,
    labels.expectedPayout, labels.lastPayout, labels.status, labels.reason,
  ];
  sheet.addRow(headers);
  report.sellers.forEach((seller) => sheet.addRow([
    seller.businessName, seller.legalBusinessName, seller.sector, seller.taxId,
    seller.accountHolderName, seller.bankName, seller.iban, seller.currency,
    seller.customerPaid, seller.commission, seller.sellerNet, seller.waiting,
    seller.eligible, seller.blocked, seller.batched, seller.paid,
    asDate(seller.oldestUnpaid), asDate(seller.nextEligibility), seller.daysRemaining,
    asDate(seller.expectedPayout), asDate(seller.lastPayout), seller.status, seller.reason,
  ]));
  styleTable(sheet, { money: [9, 10, 11, 12, 13, 14, 15, 16], dates: [17, 18, 20, 21] });
  return sheet;
}

function addTransactionSheet(workbook, report, labels) {
  const sheet = workbook.addWorksheet(labels.transactionsSheet);
  const headers = [
    labels.seller, labels.sector, labels.reference, labels.paymentDate, labels.service,
    labels.customerPaid, labels.commission, labels.sellerNet, labels.currency,
    labels.financialStatus, labels.settlementStatus, labels.payoutStatus,
    labels.eligibilityStatus, labels.eligibleDate, labels.expectedPaymentDate,
    labels.daysRemaining, labels.batchNumber, labels.paidDate, labels.paymentReference,
    labels.blockingReason, labels.requiredAction, labels.sourceCollection,
    labels.sourceDocumentId, labels.payoutIndexId,
  ];
  sheet.addRow(headers);
  report.transactions.forEach((transaction) => sheet.addRow([
    transaction.sellerName, transaction.sector, transaction.reference,
    asDate(transaction.paymentDate), transaction.service, transaction.customerPaid,
    transaction.commissionDisplay, transaction.sellerNetDisplay, transaction.currency,
    transaction.financialStatus, transaction.settlementStatus, transaction.payoutStatus,
    transaction.eligibilityStatus, asDate(transaction.eligibleDate),
    transaction.expectedPaymentDisplay, transaction.daysRemaining, transaction.batchNumber,
    asDate(transaction.paidDate), transaction.paymentReference, transaction.blockingReason,
    transaction.requiredAction, transaction.sourceCollection, transaction.sourceDocumentId,
    transaction.payoutIndexId,
  ]));
  styleTable(sheet, { money: [6], dates: [4, 14, 18] });
  return sheet;
}

async function buildFinancePayablesReportWorkbook({ report, language }) {
  const labels = report.labels;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Petsupo Finance Operations";
  workbook.title = labels.title;
  workbook.subject = labels.subtitle;
  workbook.created = new Date();
  workbook.modified = new Date();

  const summary = workbook.addWorksheet(labels.summarySheet);
  addTitle(summary, labels.title, report);
  addSummary(summary, report, labels);
  summary.getColumn(2).numFmt = MONEY_FORMAT;
  summary.getColumn(1).width = 32;
  summary.getColumn(2).width = 42;
  summary.pageSetup = { orientation: "portrait", fitToPage: true, fitToWidth: 1, fitToHeight: 1, paperSize: 9 };
  summary.headerFooter.oddFooter = labels.footer;

  addSellerSheet(workbook, report, labels);
  addTransactionSheet(workbook, report, labels);

  const notes = workbook.addWorksheet(labels.notesSheet);
  notes.addRow([labels.notesHeading]);
  notes.getRow(1).font = { bold: true, size: 14, color: { argb: "FF17324D" } };
  report.notes.forEach((note) => notes.addRow([note]));
  notes.getColumn(1).width = 110;
  notes.getColumn(1).alignment = { wrapText: true, vertical: "top" };
  notes.pageSetup = { orientation: "portrait", fitToPage: true, fitToWidth: 1, fitToHeight: 1, paperSize: 9 };

  return Buffer.from(await workbook.xlsx.writeBuffer());
}

module.exports = { buildFinancePayablesReportWorkbook };
