const Map<String, List<String>> petBreeds = {
  'dog': [
    'Afghan Hound',
    'Airedale Terrier',
    'Akita',
    'Alaskan Malamute',
    'American Bulldog',
    'American Pit Bull Terrier',
    'Australian Cattle Dog',
    'Australian Shepherd',
    'Basset Hound',
    'Beagle',
    'Belgian Malinois',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Bloodhound',
    'Border Collie',
    'Boston Terrier',
    'Boxer',
    'Bulldog',
    'Bullmastiff',
    'Cairn Terrier',
    'Cane Corso',
    'Cavalier King Charles Spaniel',
    'Chihuahua',
    'Chow Chow',
    'Cocker Spaniel',
    'Collie',
    'Dachshund',
    'Dalmatian',
    'Doberman Pinscher',
    'English Springer Spaniel',
    'French Bulldog',
    'German Shepherd',
    'German Shorthaired Pointer',
    'Golden Retriever',
    'Great Dane',
    'Great Pyrenees',
    'Havanese',
    'Irish Setter',
    'Irish Wolfhound',
    'Jack Russell Terrier',
    'Labrador Retriever',
    'Lhasa Apso',
    'Maltese',
    'Mastiff',
    'Miniature Schnauzer',
    'Newfoundland',
    'Papillon',
    'Pekingese',
    'Pomeranian',
    'Poodle',
    'Pug',
    'Rottweiler',
    'Saint Bernard',
    'Samoyed',
    'Shetland Sheepdog',
    'Shih Tzu',
    'Siberian Husky',
    'Staffordshire Bull Terrier',
    'Vizsla',
    'Weimaraner',
    'West Highland White Terrier',
    'Yorkshire Terrier',
    'Mixed',
    'Unknown',
  ],
  'cat': [
    'Persian',
    'Siamese',
    'Maine Coon',
    'British Shorthair',
    'Scottish Fold',
    'Ragdoll',
    'Bengal',
    'Sphynx',
    'Russian Blue',
    'Turkish Angora',
    'Van Cat',
    'Mixed',
    'Unknown',
  ],
  'bird': [
    'Parrot',
    'Canary',
    'Budgerigar',
    'Cockatiel',
    'Lovebird',
    'Finch',
    'Pigeon',
    'Macaw',
    'Cockatoo',
    'Mixed',
    'Unknown',
  ],
  'rabbit': [
    'Holland Lop',
    'Mini Lop',
    'Netherland Dwarf',
    'Lionhead',
    'Rex',
    'Mini Rex',
    'Flemish Giant',
    'Angora',
    'Dutch',
    'Mixed',
    'Unknown',
  ],
  'other': ['Unknown', 'Mixed', 'Other'],
};

List<String> breedsForPetType(String? petType) {
  final key = petType?.trim().toLowerCase() ?? 'dog';
  return petBreeds[key] ?? petBreeds['other']!;
}
