// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgrDy5XULhjwxMOsfGWuHdo5hNiepSQjg',
    appId: '1:188282684447:web:f0384517e41a6b7c53412a',
    messagingSenderId: '188282684447',
    projectId: 'barkymatches-new',
    authDomain: 'barkymatches-new.firebaseapp.com',
    storageBucket: 'barkymatches-new.firebasestorage.app',
    measurementId: 'G-0FXJL7LFM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_NO1hEaDryeu8Rh6tmXHn-4DdCQvWVj4',
    appId: '1:188282684447:android:38cea1857a2f204453412a',
    messagingSenderId: '188282684447',
    projectId: 'barkymatches-new',
    storageBucket: 'barkymatches-new.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgrDy5XULhjwxMOsfGWuHdo5hNiepSQjg',
    appId: '1:188282684447:web:2e04b07cfdc75dcc53412a',
    messagingSenderId: '188282684447',
    projectId: 'barkymatches-new',
    authDomain: 'barkymatches-new.firebaseapp.com',
    storageBucket: 'barkymatches-new.firebasestorage.app',
    measurementId: 'G-H9GWX3C874',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAT0G07izlYU9vT1Hfw4z487lic4KZOQ8',
    appId: '1:188282684447:ios:6615fe9c81c0766753412a',
    messagingSenderId: '188282684447',
    projectId: 'barkymatches-new',
    storageBucket: 'barkymatches-new.firebasestorage.app',
    androidClientId: '188282684447-ftf6jlcfg84lnghkkm9653grujvh42un.apps.googleusercontent.com',
    iosClientId: '188282684447-d3j7jscc680fdd4drqd27d5elko54jh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.barkyMatchesFresh',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAT0G07izlYU9vT1Hfw4z487lic4KZOQ8',
    appId: '1:188282684447:ios:6615fe9c81c0766753412a',
    messagingSenderId: '188282684447',
    projectId: 'barkymatches-new',
    storageBucket: 'barkymatches-new.firebasestorage.app',
    androidClientId: '188282684447-ftf6jlcfg84lnghkkm9653grujvh42un.apps.googleusercontent.com',
    iosClientId: '188282684447-d3j7jscc680fdd4drqd27d5elko54jh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.barkyMatchesFresh',
  );

}